# /system

/health/alive:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {}
/health/ready:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {}
